# Data Analysis on Student Performance Analysis

## Notebook 1 - Preprocessing

**Author:** Junhyuk Lee

**Date:** April 6, 2026

## Contents

- Abstract
- Imports
- Data Exploration
- Data Cleaning

---

## Abstract

In this data analysis project, we will be analyzing a dataset containing information regarding University students' lifestyle and study habits, and understanding how lifestyle and habits influence academic performance and success.

In this notebook, we will read in the University Students Performance & Study Habits for data processing and data cleaning, in preparation for Exploratory Data Analysis (EDA) and modeling.

---

## Imports

For this notebook, we only need `numpy` and `pandas` for data processing and data cleaning. We do not need any data visualization or modeling libraries.

In [11]:
import numpy as np
import pandas as pd

# Suppress warning messages
import warnings
warnings.filterwarnings("ignore")

---

## Data Exploration

First, we need to import the data using `pd.read_csv()`.

### About the dataset

This is the University Students Performance & Study Habits dataset, which is publicly available on Kaggle.

Link to dataset: [University Students Performance & Study Habits](https://www.kaggle.com/datasets/asifxzaman/university-students-performance-and-study-habits2026)

In [17]:
# Read in CSV data
path = "../data/raw/global_university_students_performance_habits_10000.csv"
students = pd.read_csv(path)
del path

Let's take a look at our dataset. We will use `df.head()` and `df.tail()` method to look at the first and last 5 rows of the dataset respectively.

In [19]:
# First 5 rows of dataset
students.head()

,student_id,age,gender,country,major,university_year,GPA,study_hours_per_day,class_attendance_percent,sleep_hours,...,internet_quality,mental_stress_level,AI_tool_usage_hours,favorite_AI_tool,note_taking_method,exam_preparation_days,coffee_consumption_per_day,extracurricular_hours_per_week,final_exam_score,assignment_score
0,S00001,23,Female,Germany,Law,4,3.81,4.2,96,6.2,...,Average,4.8,1.5,Claude,Digital,15,3,7.6,100,100
1,S00002,26,Female,USA,Economics,2,3.46,3.3,94,6.6,...,Average,3.9,2.3,Gemini,Mixed,11,3,5.2,100,83
2,S00003,18,Female,Canada,Medicine,3,4.00,4.5,100,6.3,...,Average,4.8,0.0,NaN,Mixed,12,3,4.6,100,100
3,S00004,20,Male,Australia,Physics,4,3.77,5.8,97,7.1,...,Good,5.9,2.9,Gemini,Mixed,11,1,4.0,100,98
4,S00005,28,Female,Australia,Medicine,2,4.00,3.1,96,8.4,...,Good,3.1,1.5,ChatGPT,Handwritten,15,4,1.4,100,94

In [20]:
# Last 5 rows of dataset
students.tail()

,student_id,age,gender,country,major,university_year,GPA,study_hours_per_day,class_attendance_percent,sleep_hours,...,internet_quality,mental_stress_level,AI_tool_usage_hours,favorite_AI_tool,note_taking_method,exam_preparation_days,coffee_consumption_per_day,extracurricular_hours_per_week,final_exam_score,assignment_score
9995,S09996,18,Male,Bangladesh,Psychology,1,4.00,5.5,100,7.5,...,Good,2.8,2.1,ChatGPT,Mixed,21,1,6.3,100,100
9996,S09997,24,Male,Brazil,Psychology,4,2.90,0.5,75,8.7,...,Average,3.3,0.8,Copilot,Mixed,9,1,5.1,85,95
9997,S09998,28,Male,India,Medicine,1,3.04,2.4,91,7.5,...,Good,3.5,0.7,Gemini,Digital,11,2,0.0,100,81
9998,S09999,23,Male,UK,Engineering,2,4.00,4.2,100,9.1,...,Average,1.0,1.2,Copilot,Mixed,13,4,2.6,97,97
9999,S10000,27,Male,Italy,Psychology,1,3.19,4.5,85,5.1,...,Average,4.0,0.2,NaN,Mixed,11,3,4.8,100,97

From first glance, we can see that there are a combination of categorical and numerical values.

Each row represents an individual student and their corresponding information, such as their age, gender, country, major, GPA, etc.

Let's see how many rows and columns are in this dataset, using `df.shape`.

In [23]:
n_rows, n_cols = students.shape
print(f"The `students` dataset contains {n_rows} rows and {n_cols} columns.")
del n_rows, n_cols

The `students` dataset contains 10000 rows and 27 columns.

Next, let's take a look at the summarized information of our dataset using the `df.info()` method.

In [25]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   student_id                      10000 non-null  object
 1   age                             10000 non-null  int64
 2   gender                          10000 non-null  object
 3   country                         10000 non-null  object
 4   major                           10000 non-null  object
 5   university_year                 10000 non-null  int64
 6   GPA                             10000 non-null  float64
 7   study_hours_per_day             10000 non-null  float64
 8   class_attendance_percent        10000 non-null  int64
 9   sleep_hours                     10000 non-null  float64
 10  screen_time_hours               10000 non-null  float64
 11  social_media_hours              10000 non-null  float64
 12  gaming_hours                    10000 non-null  float64
 13  exercise_hours_per_week         10000 non-null  float64
 14  part_time_job                   10000 non-null  object
 15  relationship_status             10000 non-null  object
 16  family_income_level             10000 non-null  object
 17  internet_quality                10000 non-null  object
 18  mental_stress_level             10000 non-null  float64
 19  AI_tool_usage_hours             10000 non-null  float64
 20  favorite_AI_tool                8280 non-null   object
 21  note_taking_method              10000 non-null  object
 22  exam_preparation_days           10000 non-null  int64
 23  coffee_consumption_per_day      10000 non-null  int64
 24  extracurricular_hours_per_week  10000 non-null  float64
 25  final_exam_score                10000 non-null  int64
 26  assignment_score                10000 non-null  int64
dtypes: float64(10), int64(7), object(10)
memory usage: 2.1+ MB

Let's print out the columns that are in this dataset using `df.columns`.

In [27]:
students.columns

Index(['student_id', 'age', 'gender', 'country', 'major', 'university_year',
       'GPA', 'study_hours_per_day', 'class_attendance_percent', 'sleep_hours',
       'screen_time_hours', 'social_media_hours', 'gaming_hours',
       'exercise_hours_per_week', 'part_time_job', 'relationship_status',
       'family_income_level', 'internet_quality', 'mental_stress_level',
       'AI_tool_usage_hours', 'favorite_AI_tool', 'note_taking_method',
       'exam_preparation_days', 'coffee_consumption_per_day',
       'extracurricular_hours_per_week', 'final_exam_score',
       'assignment_score'],
      dtype='object')

Let's also print the data types of each columns.

In [29]:
students.dtypes

student_id                         object
age                                 int64
gender                             object
country                            object
major                              object
university_year                     int64
GPA                               float64
study_hours_per_day               float64
class_attendance_percent            int64
sleep_hours                       float64
screen_time_hours                 float64
social_media_hours                float64
gaming_hours                      float64
exercise_hours_per_week           float64
part_time_job                      object
relationship_status                object
family_income_level                object
internet_quality                   object
mental_stress_level               float64
AI_tool_usage_hours               float64
favorite_AI_tool                   object
note_taking_method                 object
exam_preparation_days               int64
coffee_consumption_per_day          int64
extracurricular_hours_per_week    float64
final_exam_score                    int64
assignment_score                    int64
dtype: object

In [30]:
cols = list(students.columns)

for idx, col in enumerate(cols):
    print(f"{idx}:  {col}  ({students[col].dtype})")

del cols

0:  student_id  (object)
1:  age  (int64)
2:  gender  (object)
3:  country  (object)
4:  major  (object)
5:  university_year  (int64)
6:  GPA  (float64)
7:  study_hours_per_day  (float64)
8:  class_attendance_percent  (int64)
9:  sleep_hours  (float64)
10:  screen_time_hours  (float64)
11:  social_media_hours  (float64)
12:  gaming_hours  (float64)
13:  exercise_hours_per_week  (float64)
14:  part_time_job  (object)
15:  relationship_status  (object)
16:  family_income_level  (object)
17:  internet_quality  (object)
18:  mental_stress_level  (float64)
19:  AI_tool_usage_hours  (float64)
20:  favorite_AI_tool  (object)
21:  note_taking_method  (object)
22:  exam_preparation_days  (int64)
23:  coffee_consumption_per_day  (int64)
24:  extracurricular_hours_per_week  (float64)
25:  final_exam_score  (int64)
26:  assignment_score  (int64)

---

## Data Cleaning

In this section, we are going to clean the dataset before we start performing any data analysis.

We will examine the dataset for any **missing values** or **duplicates**.
For this process, we will leave out outliers is there is any.

### Missingness

Let's start with missing values. First, let's see how many missing values this dataset contains.

In [37]:
n_missing_values = students.isna().sum().sum()

print(f"This dataset has {n_missing_values} missing value(s).")

del n_missing_values

This dataset has 1720 missing value(s).

As we can see from the above output, there are missing values present in this dataset.

Next, let's examine what column(s) contain missing values.

In [39]:
students.isna().sum()

student_id                           0
age                                  0
gender                               0
country                              0
major                                0
university_year                      0
GPA                                  0
study_hours_per_day                  0
class_attendance_percent             0
sleep_hours                          0
screen_time_hours                    0
social_media_hours                   0
gaming_hours                         0
exercise_hours_per_week              0
part_time_job                        0
relationship_status                  0
family_income_level                  0
internet_quality                     0
mental_stress_level                  0
AI_tool_usage_hours                  0
favorite_AI_tool                  1720
note_taking_method                   0
exam_preparation_days                0
coffee_consumption_per_day           0
extracurricular_hours_per_week       0
final_exam_score                     0
assignment_score                     0
dtype: int64

From the above, we can see that there appears to be only one column that has missing values: `favorite_AI_tool`.

In [41]:
# Let's take a look at the unique values of `favorite_AI_tool`
students['favorite_AI_tool'].unique()

array(['Claude', 'Gemini', nan, 'ChatGPT', 'Copilot'], dtype=object)

Notice that this column is **missing by design**, meaning that the missing values are intentional, since not every student have a favorite AI tool that they prefer using.

Now, there are a few approaches we can take to handle missingness here.

One way we can handle it is to drop the column `favorite_AI_tool`, or drop the rows that contain a missing value.

However, the approach we are going to use is to actually keep the column, and replace the null entries with a string value like 'None'.
To do that, we are going to use the `.fillna()` method to fill the missing values for the column.

In [43]:
# Fill missing values for column `favorite_AI_tool`
students['favorite_AI_tool'] = students['favorite_AI_tool'].fillna("None")
students

,student_id,age,gender,country,major,university_year,GPA,study_hours_per_day,class_attendance_percent,sleep_hours,...,internet_quality,mental_stress_level,AI_tool_usage_hours,favorite_AI_tool,note_taking_method,exam_preparation_days,coffee_consumption_per_day,extracurricular_hours_per_week,final_exam_score,assignment_score
0,S00001,23,Female,Germany,Law,4,3.81,4.2,96,6.2,...,Average,4.8,1.5,Claude,Digital,15,3,7.6,100,100
1,S00002,26,Female,USA,Economics,2,3.46,3.3,94,6.6,...,Average,3.9,2.3,Gemini,Mixed,11,3,5.2,100,83
2,S00003,18,Female,Canada,Medicine,3,4.00,4.5,100,6.3,...,Average,4.8,0.0,None,Mixed,12,3,4.6,100,100
3,S00004,20,Male,Australia,Physics,4,3.77,5.8,97,7.1,...,Good,5.9,2.9,Gemini,Mixed,11,1,4.0,100,98
4,S00005,28,Female,Australia,Medicine,2,4.00,3.1,96,8.4,...,Good,3.1,1.5,ChatGPT,Handwritten,15,4,1.4,100,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,S09996,18,Male,Bangladesh,Psychology,1,4.00,5.5,100,7.5,...,Good,2.8,2.1,ChatGPT,Mixed,21,1,6.3,100,100
9996,S09997,24,Male,Brazil,Psychology,4,2.90,0.5,75,8.7,...,Average,3.3,0.8,Copilot,Mixed,9,1,5.1,85,95
9997,S09998,28,Male,India,Medicine,1,3.04,2.4,91,7.5,...,Good,3.5,0.7,Gemini,Digital,11,2,0.0,100,81
9998,S09999,23,Male,UK,Engineering,2,4.00,4.2,100,9.1,...,Average,1.0,1.2,Copilot,Mixed,13,4,2.6,97,97
9999,S10000,27,Male,Italy,Psychology,1,3.19,4.5,85,5.1,...,Average,4.0,0.2,None,Mixed,11,3,4.8,100,97

In [44]:
# Checking to make sure missing values are filled
print(f"There are {students.isna().sum().sum()} missing values.")

There are 0 missing values.

### Duplicates

The next step is to find out whether there are duplicates present, and handle duplicated data.

The simplest method to do that is to use the `df.duplicated()` method.

In [47]:
print(f"There are {students.duplicated().sum()} duplicated rows.")

There are 0 duplicated rows.

Since there are no duplicated rows, we are done.

Note that if there were duplicate rows, we can remove them via the `df.drop_duplicates()` method.

### Save Cleaned Data

Now that we are finished with cleaning the data, let's save the dataset to a CSV file using `.to_csv()`.

We are going to save it into the `../data/processed/` directory, save the data as `students_cleaned.csv`.

In [51]:
students.to_csv("../data/processed/students_cleaned.csv", index=False)

Now, we are ready to perform Exploratory Data Analysis (EDA), which we will do in the next notebook.

---